--- #YAML:1.0
name: Text-Truncate
version: 1.02
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: Perl module with simple string truncating routine
license: unrestricted
requires:
  Carp: 0
  perl: 5.004
recommends:
  Pod::Coverage: 0
  Test::Pod: 1
  Test::Prereq: 0
build_requires:
  Test::More: 0
provides:
  Text::Truncate:
    file: lib/Text/Truncate.pm
    version: 1.02
generated_by: Module::Build version 0.2607
