--- #YAML:1.0
name: Text-Truncate
version: 1.00
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: Perl module with simple string truncating routine
license: unrestricted
requires:
  Carp: 0
  perl: 5.004
build_requires:
  Test: 0
provides:
  Text::Truncate:
    file: lib/Text/Truncate.pm
    version: 1.00
generated_by: Module::Build version 0.25_02
